/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import model.bean.SisContato;
import model.bean.SisEndereco;
import model.bean.SisMedico;
import model.dao.MedicoDAO;

/**
 *
 * @author Alex
 */
public class SisTelaCadMedico extends javax.swing.JFrame {

    ResultSet rs;
    MedicoDAO mod = new MedicoDAO();
    SisMedico med = new SisMedico();
    SisEndereco end = new SisEndereco();
    SisContato ctt = new SisContato();

    private void pesquisar_medico() {

        /*connection.ConnectionFactory.getConnection();
        
        String sql = "select nomemedico from sis_medico where nomeMedico like ? ";
        try {
            PreparedStatement stmt = connection.ConnectionFactory.getConnection().prepareStatement(sql);
            //passando o conteúdo da caixa de pesquisa para o ??
            // atenção ao "% - continuação da string sql
            
            stmt.setString(1, "'%" + txPesquisar.getText() + "%'");
            ResultSet rs = stmt.executeQuery();
            //jTableMedico.setModel(DbUtils.resultSetToTableModel(rs));
            while (rs.next()) {
                med.setId(rs.getInt("id"));
                med.setNome(rs.getString("nomeMedico"));
                
                med.setEspecialidade(rs.getString("especialidade"));
                med.setCRM(rs.getInt("CRM"));
                med.setUF_CRM(rs.getString("ufCRM"));
                
                med.setNome(txNomeMed.getText());
                med.setEspecialidade(jcbEspecialidade.getSelectedItem().toString());
                med.setCRM(Integer.parseInt(txCRM.getText()));
                med.setUF_CRM(jcbUFCRM.getSelectedItem().toString());
                
                
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
        connection.ConnectionFactory.getConnection();

        String sql = "select * from sis_medico where nomeMedico like ? ";
        try {
            PreparedStatement stmt = connection.ConnectionFactory.getConnection().prepareStatement(sql);
            //passando o conteúdo da caixa de pesquisa para o ??
            // atenção ao "% - continuação da string sql

            stmt.setString(1, "%" + txPesquisar.getText() + "%");
            rs = stmt.executeQuery();

            jTableMedico.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Médico não encontrado.Tente Novamente!!");

        }
    }

    public void setar_campos() {
        int setar = jTableMedico.getSelectedRow();
        txNomeMed.setText(jTableMedico.getModel().getValueAt(setar, 1).toString());
        jcbEspecialidade.setSelectedItem(jTableMedico.getModel().getValueAt(setar, 2).toString());
        txCRM.setText(jTableMedico.getModel().getValueAt(setar, 3).toString());
        jcbUFCRM.setSelectedItem(jTableMedico.getModel().getValueAt(setar, 4).toString());
        txMedID.setText(jTableMedico.getModel().getValueAt(setar, 0).toString());
        

    }
    
    public void alterarMedico(){
        String sql = "update sis_medico set nomeMedico = ?, especialidade = ?, crm = ?, ufcrm = ? where id = ?";
        
        try {
            PreparedStatement stmt = connection.ConnectionFactory.getConnection().prepareStatement(sql);
            stmt.setString(1, txNomeMed.getText());
            stmt.setString(2, jcbEspecialidade.getSelectedItem().toString());
            stmt.setInt(3, Integer.parseInt(txCRM.getText()));
            stmt.setString(4, jcbUFCRM.getSelectedItem().toString());
            stmt.setString(5, txMedID.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Médico Alterado com Sucesso");
            txNomeMed.setText(null);
            txCRM.setText(null);
            jcbEspecialidade.setSelectedItem(1);
            jcbUFCRM.setSelectedItem(1);
            
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
    }

    /**
     * Creates new form SisTelaCadMedico
     */
    public SisTelaCadMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNomeMed = new javax.swing.JTextField();
        jcbEspecialidade = new javax.swing.JComboBox<>();
        txCRM = new javax.swing.JTextField();
        jcbUFCRM = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btCadNovo = new javax.swing.JButton();
        btCadAlterar = new javax.swing.JButton();
        btCadCancelar = new javax.swing.JButton();
        btCadSalvar = new javax.swing.JButton();
        btCadExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedico = new javax.swing.JTable();
        txPesquisar = new javax.swing.JTextField();
        btPesquisarMedico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txMedID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(207, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);

        jLabel1.setText("Nome:");

        jLabel3.setText("Especialidade:");

        jLabel4.setText("CRM:");

        jcbEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Terapia Ocupacional", "Psicoterapeuta", "Psicólogo", "Psicanalista" }));

        jcbUFCRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel5.setText("UF:");

        btCadNovo.setText("Novo");
        btCadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadNovoActionPerformed(evt);
            }
        });

        btCadAlterar.setText("Alterar");
        btCadAlterar.setEnabled(false);
        btCadAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadAlterarActionPerformed(evt);
            }
        });

        btCadCancelar.setText("Cancelar");
        btCadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadCancelarActionPerformed(evt);
            }
        });

        btCadSalvar.setText("Salvar");
        btCadSalvar.setEnabled(false);
        btCadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadSalvarActionPerformed(evt);
            }
        });

        btCadExcluir.setText("Excluir");
        btCadExcluir.setEnabled(false);

        jTableMedico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMedico);

        txPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txPesquisarKeyReleased(evt);
            }
        });

        btPesquisarMedico.setText("Pesquisar");
        btPesquisarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarMedicoActionPerformed(evt);
            }
        });

        jLabel6.setText("ID:");

        txMedID.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btCadNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(127, 127, 127))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txPesquisar)
                            .addComponent(txCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txNomeMed)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txMedID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesquisarMedico)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbUFCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadNovo)
                    .addComponent(btCadAlterar)
                    .addComponent(btCadCancelar)
                    .addComponent(btCadSalvar)
                    .addComponent(btCadExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txMedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jcbEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbUFCRM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisarMedico))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO DE MÉDICOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadCancelarActionPerformed
        // TODO add your handling code here:
        //end.
        dispose();
    }//GEN-LAST:event_btCadCancelarActionPerformed

    private void btCadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadSalvarActionPerformed
        //if (txNomeMed.equals(txNomeMed.getText()!= null) && txCRM.equals(txCRM.getText() != null) && jcbEspecialidade.equals(jcbEspecialidade.getSelectedItem()) && jcbUFCRM.equals(jcbUFCRM.getSelectedItem())) {
        med.setNome(txNomeMed.getText());
        med.setEspecialidade(jcbEspecialidade.getSelectedItem().toString());
        med.setCRM(Integer.parseInt(txCRM.getText()));
        med.setUF_CRM(jcbUFCRM.getSelectedItem().toString());
        mod.salvarMedico(med);
        txNomeMed.setText("");
        txCRM.setText("");
        jcbEspecialidade.setSelectedItem(1);
        jcbUFCRM.setSelectedItem(1);
        
        //} else {
        //  JOptionPane.showMessageDialog(null, "Preencha os Campos!!");
        //}
    }//GEN-LAST:event_btCadSalvarActionPerformed

    private void btPesquisarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarMedicoActionPerformed
        if (!txPesquisar.equals(txPesquisar.getText().isEmpty())) {
            med.setPesquisa(txPesquisar.getText());
            SisMedico model = mod.buscaMedico(med);
            txNomeMed.setText(model.getNome());
            jcbEspecialidade.setSelectedItem(model.getEspecialidade());
            txCRM.setText(String.valueOf(model.getCRM()));
            jcbUFCRM.setSelectedItem(model.getUF_CRM());
            txMedID.setText(String.valueOf(model.getId()));

            jTableMedico.setModel(DbUtils.resultSetToTableModel(rs));

            if (model == model) {
                btCadAlterar.setEnabled(true);
                btCadExcluir.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "not found");
            }
        } else {
            txNomeMed.setText("");
            txCRM.setText("");
            jcbEspecialidade.setSelectedItem(0);
            jcbUFCRM.setSelectedItem(0);
        }
    }//GEN-LAST:event_btPesquisarMedicoActionPerformed

    private void btCadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadNovoActionPerformed
        txNomeMed.setText("");
        txCRM.setText("");
        txPesquisar.setText("");
        jcbEspecialidade.setSelectedItem(0);
        jcbUFCRM.setSelectedItem(0);

        txPesquisar.setEnabled(false);
        btPesquisarMedico.setEnabled(false);

        btCadSalvar.setEnabled(true);
        btCadAlterar.setEnabled(true);
        btCadExcluir.setEnabled(true);
        txNomeMed.setEnabled(true);
        txCRM.setEnabled(true);
        jcbEspecialidade.setEnabled(true);
        jcbUFCRM.setEnabled(true);

    }//GEN-LAST:event_btCadNovoActionPerformed

    private void txPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar_medico();

    }//GEN-LAST:event_txPesquisarKeyReleased

    private void jTableMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedicoMouseClicked
        // TODO add your handling code here:
        
        //evento para setar os campos da tabela. (clicar com o mouse)
        setar_campos();
        btCadAlterar.setEnabled(true);
        btCadSalvar.setEnabled(false);
        
    }//GEN-LAST:event_jTableMedicoMouseClicked

    private void btCadAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadAlterarActionPerformed
        // TODO add your handling code here:
        alterarMedico();
    }//GEN-LAST:event_btCadAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisTelaCadMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisTelaCadMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisTelaCadMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisTelaCadMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisTelaCadMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadAlterar;
    private javax.swing.JButton btCadCancelar;
    private javax.swing.JButton btCadExcluir;
    private javax.swing.JButton btCadNovo;
    private javax.swing.JButton btCadSalvar;
    private javax.swing.JButton btPesquisarMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedico;
    private javax.swing.JComboBox<String> jcbEspecialidade;
    private javax.swing.JComboBox<String> jcbUFCRM;
    private javax.swing.JTextField txCRM;
    private javax.swing.JTextField txMedID;
    private javax.swing.JTextField txNomeMed;
    private javax.swing.JTextField txPesquisar;
    // End of variables declaration//GEN-END:variables
}
