package view;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import model.bean.SisMedico;
import model.bean.SisPaciente;
import model.bean.SisTipoConsulta;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Alex
 */
public class SisTelaConsulta extends javax.swing.JFrame {

    SisPaciente pac = new SisPaciente();
    SisMedico med = new SisMedico();
    SisTipoConsulta cons = new SisTipoConsulta();
    
    public SisPaciente buscarPaciente(SisPaciente pac){
        String sql = "select id,nomePessoa from sis_paciente where nomePessoa like '%"+pac.getNomePaciente()+"%' ";
        try {
            PreparedStatement stmt = connection.ConnectionFactory.getConnection().prepareStatement(sql);
            
            ResultSet rs = stmt.executeQuery();
            
            rs.first();
            pac.setId(rs.getInt("id"));
                pac.setNomePaciente(rs.getString("nomePessoa"));
                
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Paciente não encontrado.Tente Novamente!!");
            
        }
        return pac;
    }
    public SisMedico buscarMedico (SisMedico med){
        String sql = "select id,nomeMedico from sis_medico where nomeMedico like '%"+med.getNome()+"%' ";
        try {
            PreparedStatement stmt = connection.ConnectionFactory.getConnection().prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            rs.first();
            med.setId(rs.getInt("id"));
                med.setNome(rs.getString("nomeMedico"));
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Médico não encontrado.Tente Novamente!!");
            
        }
        return med;
    }
    
    public void pesquisar_consultaPaciente(){
        connection.ConnectionFactory.getConnection();
        String sql = "select nomePessoa from sis_paciente where nomePessoa like ?";
        try {
            PreparedStatement stmt = connection.ConnectionFactory.getConnection().prepareStatement(sql);
            stmt.setString(1, "%"+txPesqPaciente.getText()+"%");
            
            
            ResultSet rs = stmt.executeQuery();
            jTablePesqPaciente.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void pesquisar_consultaMedico(){
        connection.ConnectionFactory.getConnection();
        String sql = "select nomeMedico from sis_medico where nomeMedico like ?";
        try {
            PreparedStatement stmt = connection.ConnectionFactory.getConnection().prepareStatement(sql);
            stmt.setString(1, "%"+txPesqMedico.getText()+"%");
            
            
            ResultSet rs = stmt.executeQuery();
            jTablePesqMedico.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void salvarTriagem(SisPaciente pac, SisMedico med, SisTipoConsulta consult){
        String sql = "insert into sis_tipoConsulta (nomeConsulta,CID,horario,paciente_id, medico_id) values(?,?,?,?,?)";
        try{
        PreparedStatement stmt = connection.ConnectionFactory.getConnection().prepareStatement(sql);
        stmt.setString(1, jcbTriagemTerapia.getSelectedItem().toString());
        stmt.setString(2,txTriagemCID.getText());
        String dia = txFormDataHora.getText().substring(0, 2);
        String mes = txFormDataHora.getText().substring(3, 5);
        String ano = txFormDataHora.getText().substring(6, 10);
        String hora = txFormDataHora.getText().substring(11, 13);
        String minuto = txFormDataHora.getText().substring(14, 16);
        String dtBanco = ano + "-" + mes + "-" + dia + " " +hora+":"+minuto;
        stmt.setString(3, dtBanco);
        stmt.setInt(4, Integer.parseInt(idPaciente.getText()));
        stmt.setInt(5, Integer.parseInt(idMedico.getText()));
        
        stmt.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Consulta Marcada!!!");
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "não Cadastrado"+ex);
        }
    }
    
    /** Creates new form SisTelaConsulta */
    public SisTelaConsulta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txTriagemPaciente = new javax.swing.JTextField();
        txTriagemMedico = new javax.swing.JTextField();
        jcbTriagemTerapia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btTriagemSalvar = new javax.swing.JButton();
        btTriagemCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idPaciente = new javax.swing.JTextField();
        idMedico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txTriagemCID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txFormDataHora = new javax.swing.JFormattedTextField();
        txPesqPaciente = new javax.swing.JTextField();
        txPesqMedico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesqMedico = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesqPaciente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Paciente:");

        jLabel3.setText("Médico:");

        jLabel4.setText("Triagem:");

        txTriagemPaciente.setEnabled(false);

        txTriagemMedico.setEnabled(false);

        jcbTriagemTerapia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Terapia Individual", "Terapia em Grupo", "Terapia Familiar" }));

        btTriagemSalvar.setText("Salvar");
        btTriagemSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTriagemSalvarActionPerformed(evt);
            }
        });

        btTriagemCancelar.setText("Cancelar");
        btTriagemCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTriagemCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        idPaciente.setEnabled(false);

        idMedico.setEnabled(false);

        jLabel6.setText("ID Paciente:");

        jLabel7.setText("ID Médico: ");

        jLabel8.setText("CID:");

        jLabel9.setText("Horário:");

        try {
            txFormDataHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txPesqPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txPesqPacienteKeyReleased(evt);
            }
        });

        txPesqMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txPesqMedicoKeyReleased(evt);
            }
        });

        jTablePesqMedico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePesqMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÉDICO"
            }
        ));
        jScrollPane1.setViewportView(jTablePesqMedico);

        jTablePesqPaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTablePesqPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PACIENTE"
            }
        ));
        jScrollPane2.setViewportView(jTablePesqPaciente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(idPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(idMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(txTriagemPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(txTriagemMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txPesqPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addGap(79, 79, 79)
                        .addComponent(txPesqMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jcbTriagemTerapia, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txTriagemCID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(239, 239, 239)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(txFormDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btTriagemSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btTriagemCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(idPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addComponent(idMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTriagemPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTriagemMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txPesqPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPesqMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(jcbTriagemTerapia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txFormDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTriagemCID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTriagemSalvar)
                    .addComponent(btTriagemCancelar))
                .addGap(65, 65, 65))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Triagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txPesqMedicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesqMedicoKeyReleased
        // TODO add your handling code here:
        pesquisar_consultaMedico();
    }//GEN-LAST:event_txPesqMedicoKeyReleased

    private void txPesqPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesqPacienteKeyReleased
        // TODO add your handling code here:
        pesquisar_consultaPaciente();
    }//GEN-LAST:event_txPesqPacienteKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        med.setNome(txTriagemMedico.getText());
        SisMedico medico = buscarMedico(med);
        idMedico.setText(String.valueOf(medico.getId()));
        txTriagemMedico.setText(medico.getNome());

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pac.setNomePaciente(txPesqPaciente.getText());
        SisPaciente paciente = buscarPaciente(pac);
        idPaciente.setText(String.valueOf(paciente.getId()));

        txTriagemPaciente.setText(paciente.getNomePaciente());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btTriagemCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTriagemCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btTriagemCancelarActionPerformed

    private void btTriagemSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTriagemSalvarActionPerformed
        // TODO add your handling code here:
        //pac.setNomePaciente(txTriagemPaciente.getText());
        //med.setNome(txTriagemMedico.getText());
        salvarTriagem(pac, med, cons);

    }//GEN-LAST:event_btTriagemSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisTelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisTelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisTelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisTelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisTelaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTriagemCancelar;
    private javax.swing.JButton btTriagemSalvar;
    private javax.swing.JTextField idMedico;
    private javax.swing.JTextField idPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePesqMedico;
    private javax.swing.JTable jTablePesqPaciente;
    private javax.swing.JComboBox<String> jcbTriagemTerapia;
    private javax.swing.JFormattedTextField txFormDataHora;
    private javax.swing.JTextField txPesqMedico;
    private javax.swing.JTextField txPesqPaciente;
    private javax.swing.JTextField txTriagemCID;
    private javax.swing.JTextField txTriagemMedico;
    private javax.swing.JTextField txTriagemPaciente;
    // End of variables declaration//GEN-END:variables

}
