/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class SisTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form SisTelaPrincipal
     */
    public SisTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnInicio = new javax.swing.JMenu();
        mnCadastro = new javax.swing.JMenu();
        miPaciente = new javax.swing.JMenuItem();
        miMedico = new javax.swing.JMenuItem();
        mnConsulta = new javax.swing.JMenu();
        miMarcarConsulta = new javax.swing.JMenuItem();
        miPesquisarConsulta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnInicio.setText("Inicio");
        mnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInicioActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnInicio);

        mnCadastro.setText("Cadastro");

        miPaciente.setText("Paciente");
        miPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPacienteActionPerformed(evt);
            }
        });
        mnCadastro.add(miPaciente);

        miMedico.setText("Médicos");
        mnCadastro.add(miMedico);

        jMenuBar1.add(mnCadastro);

        mnConsulta.setText("Consultas");

        miMarcarConsulta.setText("Marcar Consulta");
        mnConsulta.add(miMarcarConsulta);

        miPesquisarConsulta.setText("Pesquisar Consultas");
        mnConsulta.add(miPesquisarConsulta);

        jMenuBar1.add(mnConsulta);

        jMenu1.setText("Sair");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInicioActionPerformed
        // TODO add your handling code here:
        SisTelaPrincipal tp = new SisTelaPrincipal();
        tp.setVisible(true);
        //dispose();
    }//GEN-LAST:event_mnInicioActionPerformed

    private void miPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPacienteActionPerformed
        // TODO add your handling code here:
        SisTelaCad consulta = new SisTelaCad();
        jDesktopPane1.add(consulta);
        consulta.setVisible(true);
        
    }//GEN-LAST:event_miPacienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Ok", "Cancelar"};
        int opcao = JOptionPane.showOptionDialog(null,"Deseja reealmente sair? ", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(opcao == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem miMarcarConsulta;
    private javax.swing.JMenuItem miMedico;
    private javax.swing.JMenuItem miPaciente;
    private javax.swing.JMenuItem miPesquisarConsulta;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnConsulta;
    private javax.swing.JMenu mnInicio;
    // End of variables declaration//GEN-END:variables
}
